openapi: "3.0.0"
info:
    title: Eduction service
    version: "1.0"
    description: "
    - предоставляет информацию о курсах \n
    - позволяет составлять индивидуальные планы развития сотрудника \n
    - позволяет отслеживать прогресс выполнения курсов (api образовательных платформ) \n
    - позволяет отслеживать прогресс выполнения индивидуальных планов развития
    "
paths:
    /courses:
        get:
          description: Список доступных курсов
          responses:
            200:
              description: test
              content:
                "application/json":
                  schema:
                    type: array
                    items:
                      $ref: "#/components/schemas/course"

        post:
          description: Добавить курс
          responses:
            200:
              description: test


components:
  schemas:
    course:
      properties:
        id:
          type: integer
        name:
          type: string